// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUHrT0ncEmavrIWZNdrVNSSlGvs0GcM4g',
    appId: '1:133599635280:web:8d0d009f8add632ad22e55',
    messagingSenderId: '133599635280',
    projectId: 'expense-tracker-nhat-2026',
    authDomain: 'expense-tracker-nhat-2026.firebaseapp.com',
    storageBucket: 'expense-tracker-nhat-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUmaO0mOjAIrY0VliFuL96j5Zn5RwRlcc',
    appId: '1:133599635280:android:0efaacb2a77c7e7ed22e55',
    messagingSenderId: '133599635280',
    projectId: 'expense-tracker-nhat-2026',
    storageBucket: 'expense-tracker-nhat-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsV8SC4ElYS6SfACrOcgIHGmJo6dXFh8M',
    appId: '1:133599635280:ios:f696ee583411f2ffd22e55',
    messagingSenderId: '133599635280',
    projectId: 'expense-tracker-nhat-2026',
    storageBucket: 'expense-tracker-nhat-2026.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsV8SC4ElYS6SfACrOcgIHGmJo6dXFh8M',
    appId: '1:133599635280:ios:f696ee583411f2ffd22e55',
    messagingSenderId: '133599635280',
    projectId: 'expense-tracker-nhat-2026',
    storageBucket: 'expense-tracker-nhat-2026.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUHrT0ncEmavrIWZNdrVNSSlGvs0GcM4g',
    appId: '1:133599635280:web:460ee7d29e2e573bd22e55',
    messagingSenderId: '133599635280',
    projectId: 'expense-tracker-nhat-2026',
    authDomain: 'expense-tracker-nhat-2026.firebaseapp.com',
    storageBucket: 'expense-tracker-nhat-2026.firebasestorage.app',
  );
}
